<?php
use App\Migrator\Seeder;

class ServicesSeeder extends Seeder {
    public function run() {
        $this->insertIfEmpty('settings_home_services', [
            'hash_id'       => '10003',
            'input_label'   => 'What We Do',
            'input_title'   => 'Cleaning Services Tailored to Your Needs',
            'text_subtitle' => 'From full end-of-tenancy deep cleans to regular domestic and commercial contracts — we cover everything Edinburgh landlords and businesses need.',
        ]);

        $this->insertMissing('panel_services', [
            [
                'hash_id'               => '30001',
                'input_slug'            => 'end-of-tenancy-clean',
                'input_icon'            => 'fa-solid fa-broom',
                'input_badge'           => 'MOST POPULAR',
                'input_title'           => 'End-of-Tenancy Deep Clean',
                'text_description'      => 'Full letting-standard deep clean between tenancies. Every room, every appliance, every surface — to inspection standard. Fixed price, no hidden extras.',
                'text_full_description' => "Our end-of-tenancy deep clean is designed to meet the strict standards required by letting agents and landlords across Edinburgh. We clean every room from top to bottom — including inside ovens, behind appliances, limescale removal, window sills, skirting boards, and more.\n\nEvery clean follows our professional checklist that covers all the areas inventory clerks inspect. We stay until the job is done — not until the clock runs out.",
                'text_whats_included'   => implode("\n", [
                    'Full kitchen deep clean (oven, hob, extractor, fridge/freezer inside & out)',
                    'Bathroom descale and sanitisation',
                    'All rooms dusted, vacuumed, and mopped',
                    'Skirting boards, light switches, and door frames',
                    'Inside windows and window sills',
                    'Cupboards and wardrobes wiped inside',
                    'Wall spot-cleaning for marks and scuffs',
                ]),
                'input_duration'        => '3 – 9 hours depending on property size',
                'input_starting_price'  => 'From £100 (studio) to £345 (4-bed)',
                'input_meta_title'      => 'End-of-Tenancy Cleaning Edinburgh | NextShine Cleaning',
                'text_meta_description' => 'Professional end-of-tenancy deep cleaning in Edinburgh. Fixed prices, fully insured, letting-agent approved. Book your EOT clean today.',
                'input_price_tag'       => 'From £130 (1-bed)',
                'input_link_text'       => 'View prices →',
                'input_link_url'        => '#pricing',
                'input_order'           => '1',
                'bgcolor_card_start'    => '#1A335C',
                'bgcolor_card_end'      => '#00878A',
                'date_created'          => '2026-04-10',
            ],
            [
                'hash_id'               => '30002',
                'input_slug'            => 'regular-domestic-cleaning',
                'input_icon'            => 'fa-solid fa-house-chimney',
                'input_badge'           => 'REGULAR',
                'input_title'           => 'Regular Domestic Cleaning',
                'text_description'      => 'Weekly or fortnightly cleaning for residential properties. Same team every visit, consistent results, and flexible scheduling around your life.',
                'text_full_description' => "Our regular domestic cleaning service gives you a consistently clean home without the hassle. We assign the same team to your property every visit so they learn your space, your preferences, and your standards.\n\nWhether you need weekly or fortnightly visits, we work around your schedule and always bring our own professional-grade products and equipment.",
                'text_whats_included'   => implode("\n", [
                    'All rooms vacuumed and mopped',
                    'Kitchen surfaces, hob, and sink cleaned',
                    'Bathroom cleaned and sanitised',
                    'Dusting of all accessible surfaces',
                    'Bed making (on request)',
                    'Bins emptied',
                    'All cleaning products supplied',
                ]),
                'input_duration'        => 'Minimum 2 hours per visit',
                'input_starting_price'  => '£21 per hour',
                'input_meta_title'      => 'Regular Domestic Cleaning Edinburgh | NextShine Cleaning',
                'text_meta_description' => 'Affordable weekly and fortnightly domestic cleaning in Edinburgh. Same team every visit. £21/hr. All products included.',
                'input_price_tag'       => '£21/hr (min. 2hrs)',
                'input_link_text'       => 'View prices →',
                'input_link_url'        => '#pricing',
                'input_order'           => '2',
                'bgcolor_card_start'    => '#1A335C',
                'bgcolor_card_end'      => '#2d5a9e',
                'date_created'          => '2026-04-10',
            ],
            [
                'hash_id'               => '30003',
                'input_slug'            => 'commercial-office-cleaning',
                'input_icon'            => 'fa-solid fa-building',
                'input_badge'           => 'COMMERCIAL',
                'input_title'           => 'Commercial & Office Cleaning',
                'text_description'      => 'Regular morning, evening, or weekend cleans for offices, studios, clinics, and retail spaces. Flexible contracts to suit your business hours.',
                'text_full_description' => "We provide reliable commercial cleaning for offices, studios, clinics, and retail spaces across Edinburgh. Our flexible contracts let you choose morning, evening, or weekend slots to minimise disruption to your business.\n\nWhether you need daily, weekly, or fortnightly cleans, we deliver consistent results and can invoice monthly for ease of accounting.",
                'text_whats_included'   => implode("\n", [
                    'Desk and workstation cleaning',
                    'Kitchen and break room cleaning',
                    'Bathroom and toilet sanitisation',
                    'Floor vacuuming and mopping',
                    'Bin emptying and liner replacement',
                    'Glass and surface wiping',
                    'All products and equipment supplied',
                ]),
                'input_duration'        => 'Minimum 2 hours per session',
                'input_starting_price'  => 'From £18 – £20 per hour',
                'input_meta_title'      => 'Commercial & Office Cleaning Edinburgh | NextShine Cleaning',
                'text_meta_description' => 'Professional office and commercial cleaning in Edinburgh. Flexible contracts, competitive rates, fully insured.',
                'input_price_tag'       => 'From £18–£20/hr',
                'input_link_text'       => 'View prices →',
                'input_link_url'        => '#pricing',
                'input_order'           => '3',
                'bgcolor_card_start'    => '#0f2440',
                'bgcolor_card_end'      => '#1A335C',
                'date_created'          => '2026-04-10',
            ],
            [
                'hash_id'               => '30004',
                'input_slug'            => 'one-off-deep-clean',
                'input_icon'            => 'fa-solid fa-wand-magic-sparkles',
                'input_badge'           => '',
                'input_title'           => 'One-Off Deep Clean',
                'text_description'      => 'Comprehensive deep clean for properties that need a reset. Perfect for void periods, spring cleans, or properties with long-term tenants.',
                'text_full_description' => "Our one-off deep clean is perfect for properties that need a thorough reset. Whether it is a spring clean, preparing a property for sale, or catching up after a long tenancy — we deliver a comprehensive clean from top to bottom.\n\nWe focus on the areas that regular cleaning often misses: behind appliances, inside cupboards, deep carpet cleaning, and full bathroom descaling.",
                'text_whats_included'   => implode("\n", [
                    'Every room deep cleaned floor to ceiling',
                    'Inside oven, fridge, and all appliances',
                    'Bathroom deep descale and grout cleaning',
                    'All surfaces wiped and polished',
                    'Skirting boards, light fittings, and vents',
                    'Inside windows cleaned',
                    'Carpets vacuumed (steam cleaning available as add-on)',
                ]),
                'input_duration'        => 'Quoted per property',
                'input_starting_price'  => 'Fixed price quoted on enquiry',
                'input_meta_title'      => 'One-Off Deep Cleaning Edinburgh | NextShine Cleaning',
                'text_meta_description' => 'Comprehensive one-off deep cleaning for Edinburgh homes. Perfect for spring cleans, void periods, or property resets.',
                'input_price_tag'       => 'Fixed price quoted',
                'input_link_text'       => 'Get a quote →',
                'input_link_url'        => '#contact',
                'input_order'           => '4',
                'bgcolor_card_start'    => '#00878A',
                'bgcolor_card_end'      => '#00B4B7',
                'date_created'          => '2026-04-10',
            ],
            [
                'hash_id'               => '30005',
                'input_slug'            => 'post-construction-clean',
                'input_icon'            => 'fa-solid fa-hammer',
                'input_badge'           => '',
                'input_title'           => 'Post-Construction Clean',
                'text_description'      => 'Deep clean following renovation or building works. Removes dust, debris, paint marks, and adhesive residue — market-ready or move-in ready.',
                'text_full_description' => "After renovations or building works, your property needs specialist cleaning to remove construction dust, debris, paint marks, adhesive residue, and plaster dust that normal cleaning cannot handle.\n\nOur post-construction cleaning gets your property market-ready or move-in ready. We work with builders, developers, and homeowners across Edinburgh.",
                'text_whats_included'   => implode("\n", [
                    'Removal of all construction dust and debris',
                    'Paint and adhesive residue removal',
                    'Window and glass cleaning',
                    'All surfaces wiped and polished',
                    'Floor scrubbing and mopping',
                    'Bathroom and kitchen deep clean',
                    'Final inspection walkthrough',
                ]),
                'input_duration'        => 'Quoted per project',
                'input_starting_price'  => 'Fixed price quoted on enquiry',
                'input_meta_title'      => 'Post-Construction Cleaning Edinburgh | NextShine Cleaning',
                'text_meta_description' => 'Specialist post-construction and after-builders cleaning in Edinburgh. Dust, debris, and residue removal. Market-ready results.',
                'input_price_tag'       => 'Fixed price quoted',
                'input_link_text'       => 'Get a quote →',
                'input_link_url'        => '#contact',
                'input_order'           => '5',
                'bgcolor_card_start'    => '#00878A',
                'bgcolor_card_end'      => '#005e61',
                'date_created'          => '2026-04-10',
            ],
            [
                'hash_id'               => '30006',
                'input_slug'            => 'airbnb-short-let-cleaning',
                'input_icon'            => 'fa-solid fa-key',
                'input_badge'           => 'SHORT-LET',
                'input_title'           => 'AirBnB & Short-Let Turnover',
                'text_description'      => 'Fast, reliable turnaround cleans between guests. We work to your check-out and check-in schedule — keeping your ratings high and guests happy.',
                'text_full_description' => "We provide fast, reliable turnaround cleans between short-let guests. We work to your check-out and check-in schedule — keeping your property in top condition, your ratings high, and your guests happy.\n\nWe can also provide linen changes, restocking essentials, and property checks as part of a managed package for Airbnb hosts and short-let operators.",
                'text_whats_included'   => implode("\n", [
                    'Full property clean between guests',
                    'Bathroom and kitchen deep clean',
                    'Bed linen change (linen supply available)',
                    'Toiletries and essentials restock check',
                    'Bins emptied and fresh liners',
                    'All surfaces wiped and floors cleaned',
                    'Damage and maintenance issue reporting',
                ]),
                'input_duration'        => '1.5 – 3 hours per turnover',
                'input_starting_price'  => 'From £21 per hour',
                'input_meta_title'      => 'Airbnb & Short-Let Cleaning Edinburgh | NextShine Cleaning',
                'text_meta_description' => 'Reliable Airbnb and short-let turnover cleaning in Edinburgh. Fast turnarounds, linen changes, and guest-ready results.',
                'input_price_tag'       => 'From £21/hr',
                'input_link_text'       => 'Get a quote →',
                'input_link_url'        => '#contact',
                'input_order'           => '6',
                'bgcolor_card_start'    => '#ff5a5f',
                'bgcolor_card_end'      => '#c81d25',
                'date_created'          => '2026-04-10',
            ],
        ]);
    }
}
