<?php
/**
 * Database connection. $conn is used throughout the app and admin panel.
 */

define("DBHOST", getenv('DB_HOST') ?: 'localhost');
define("DBNAME", getenv('DB_NAME'));
// The core/ layer writes this key as DB_USERNAME; accept either spelling so a
// config generated by core/create_config.php still works here.
define("DBUSER", getenv('DB_USER') ?: getenv('DB_USERNAME'));
define("DBPASS", getenv('DB_PASSWORD'));

try {
    $conn = new PDO('mysql:host=' . DBHOST . ';dbname=' . DBNAME, DBUSER, DBPASS);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {

    /**
     * Fail closed, twice over.
     *
     * A config flag alone is not enough to justify printing the database user,
     * host and name onto a public page: PRODUCTION_MODE=false is the default in
     * several of the generated config templates, so it turns up on real servers
     * by accident. Details therefore require BOTH an explicit dev flag AND a
     * request that actually originates locally.
     */
    $devFlag = getenv('PRODUCTION_MODE') === 'false';

    $remote = $_SERVER['REMOTE_ADDR'] ?? '';
    $isLocalRequest = PHP_SAPI === 'cli'
        || in_array($remote, ['127.0.0.1', '::1'], true)
        || str_starts_with($remote, '10.')
        || str_starts_with($remote, '192.168.')
        || preg_match('/^172\.(1[6-9]|2\d|3[01])\./', $remote) === 1;

    error_log('DB connection failed (' . DBUSER . '@' . DBHOST . '/' . DBNAME . '): ' . $e->getMessage());

    if ($devFlag && $isLocalRequest) {
        die('Database connection failed (' . DBUSER . '@' . DBHOST . '/' . DBNAME . '): ' . $e->getMessage());
    }

    http_response_code(503);
    header('Retry-After: 300');
    die('The site is temporarily unavailable. Please try again shortly.');
}
